class WaterSector : SoundEnvironment
{
    Default
    {
		//$Category AREAG-Map Tools
		//$Title Water Sector
		//$Sprite E0WAA0
		//$ClearArgs
		//$NotAngled
        height 3;
        radius 3;
        +DORMANT;
        -NOSECTOR;
        -NOBLOCKMAP;
        +THRUACTORS;
        +CANPASS;
        renderstyle "none";
    }
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 ACS_NamedExecuteAlways("movement_water_map", 0);
		TNT1 A 1;
		goto Super::Spawn;
	}
}
