#include "zscript/definitions.zsc"

// BASE CLASSES
#include "zscript/_baseclasses/AREAG_Common.zsc"
#include "zscript/_baseclasses/BasicActor_Virtuals.zsc"
#include "zscript/_baseclasses/BasicActionProp.zsc"
#include "zscript/_baseclasses/BasicActor.zsc"
#include "zscript/_baseclasses/BasicActor_damage.zsc"
#include "zscript/_baseclasses/BasicEffect.zsc"
#include "zscript/_baseclasses/BasicProjectile.zsc"
#include "zscript/_baseclasses/StoneBody.zsc"
#include "zscript/_baseclasses/AGCVar.zsc"
#include "zscript/_baseclasses/AGBinder.zsc"

// DATABASE SYSTEM DEFINITIONS
#include "zscript/database/mapdata.zsc"
#include "zscript/database/movingsectors.zsc"

// GRAPHIC EFFECTS
#include "zscript/effects/splashes.zsc"

// PLAYER SYSTEM DEFINITIONS
#include "zscript/player/__protoplayer.zsc"
#include "zscript/player/0_playerbase.zsc"
#include "zscript/player/1_playermove.zsc"
#include "zscript/player/2_playerhealth.zsc"
#include "zscript/player/3_playerstatus.zsc"
#include "zscript/player/4_playerproperties.zsc"

// WEAPONS
#include "zscript/inventory/actives/__baseactivetrigger.zsc"
#include "zscript/inventory/subweapons/__subwepdefs.zsc"

#include "zscript/inventory/__weaponbase.zsc"
#include "zscript/inventory/_subweaponbase.zsc"
#include "zscript/inventory/_mainweaponbase.zsc"
#include "zscript/inventory/mainweapons/1_whip.zsc"
#include "zscript/inventory/mainweapons/2_steeltyrant.zsc"
#include "zscript/inventory/mainweapons/3_capitalpunishment.zsc"
#include "zscript/inventory/mainweapons/4_ironshield.zsc"
#include "zscript/inventory/mainweapons/5_kinderlun.zsc"
#include "zscript/inventory/mainweapons/6_gravgloves.zsc"

#include "zscript/inventory/subweapons/_empty.zsc"
#include "zscript/inventory/subweapons/1_knives.zsc"
#include "zscript/inventory/subweapons/2_seeds.zsc"
#include "zscript/inventory/subweapons/3_dynamite.zsc"
#include "zscript/inventory/subweapons/4_soullamp.zsc"
#include "zscript/inventory/subweapons/5_bola.zsc"
#include "zscript/inventory/subweapons/6_gun.zsc"

// ACTIVE ITEMS
#include "zscript/inventory/actives/drone.zsc"
#include "zscript/inventory/actives/horn.zsc"
#include "zscript/inventory/actives/timepiece.zsc"
#include "zscript/inventory/actives/pauldron.zsc" // [TODO] - Animation to enable/disable, add passive functionality
#include "zscript/inventory/actives/cloak.zsc" // [TODO] - Animation to enable/disable, transparency effects

// PASSIVE ITEMS
#include "zscript/inventory/passives/_BasicPassive.zsc"
#include "zscript/inventory/passives/gearboots.zsc"
#include "zscript/inventory/passives/steamboots.zsc"
#include "zscript/inventory/passives/jetpack.zsc"
#include "zscript/inventory/passives/keys.zsc"
#include "zscript/inventory/passives/pendant.zsc"
#include "zscript/inventory/passives/cuirass.zsc"
#include "zscript/inventory/passives/shadowmeld.zsc"

#include "zscript/inventory/passives/scrolls/efficientvandal.zsc"
#include "zscript/inventory/passives/scrolls/shockabsorber.zsc"
#include "zscript/inventory/passives/scrolls/swimminglessons.zsc"

#include "zscript/inventory/hats/_BasicHat.zsc"
#include "zscript/inventory/hats/MiningHat.zsc"
#include "zscript/inventory/hats/TopHat.zsc"
#include "zscript/inventory/hats/BatteryHat.zsc"

#include "zscript/inventory/basicinventory.zsc"
#include "zscript/inventory/currency.zsc"

// STATUS EFFECTS
#include "zscript/status/curse.zsc"

// MAP TOOLS
#include "zscript/maptools/automap/automap.dropdown.zsc"
#include "zscript/maptools/automap/automap.doorway.zsc"
#include "zscript/maptools/automap/automap.enter.zsc"
#include "zscript/maptools/automap/automap.entity.zsc"
#include "zscript/maptools/automap/automap.repo.zsc"
#include "zscript/maptools/areagate.zsc"
#include "zscript/maptools/breakwall.zsc"
#include "zscript/maptools/doormanager.zsc"
#include "zscript/maptools/pitsector.zsc"
#include "zscript/maptools/roomcontroller.zsc"
#include "zscript/maptools/savepoint.zsc"
#include "zscript/maptools/shop.zsc"
#include "zscript/maptools/switches.zsc"
#include "zscript/maptools/tablet.zsc"
#include "zscript/maptools/watersector.zsc"

// MONSTERS
#include "zscript/monsters/__monsterbase.zsc"
#include "zscript/monsters/__monsterpathing.zsc"

#include "zscript/monsters/1_golem.zsc"
#include "zscript/monsters/2_glowfly.zsc"
#include "zscript/monsters/3_melee-rush.zsc"
#include "zscript/monsters/4_ranged.zsc"

// PROPS
#include "zscript/props/0_general/jars.zsc"
#include "zscript/props/0_general/blocks.zsc"
#include "zscript/props/0_general/npcs.zsc"

#include "zscript/props/1_gateway/darttrap.zsc"
#include "zscript/props/1_gateway/lasertrap.zsc"
#include "zscript/props/1_gateway/speartrap.zsc"

#include "zscript/props/2_study/StudyBookCase.zsc"
#include "zscript/props/2_study/StudySlideRing.zsc"

#include "zscript/props/3_Impact/0_General.zsc"
#include "zscript/props/3_impact/MiningPlatform.zsc"

// STATUS BARS AND MENUS
#include "zscript/sbar/AREAGStatusBar.zsc"
#include "zscript/sbar/menutools.zsc"
#include "zscript/menus/Stateman.zsc"

// List of ZForms changes listed in ExInclude.zsc
#include "zscript/menus/ZForms/ZFinclude.zsc"
#include "zscript/menus/ZForms_Extensions/ExInclude.zsc"

#include "zscript/menus/Journal/_JournalShared.zsc"
#include "zscript/menus/Journal/3_SatchelMenu.zsc"
#include "zscript/menus/Journal/4_SettingsMenu.zsc"
#include "zscript/menus/Journal/4.1_ControllerCalibrateMenu.zsc"

#include "zscript/menus/LoadMenu.zsc"
#include "zscript/menus/Debug/DBMenuBase.zsc"

#include "zscript/menus/Dialogue/DialogueMessage.zsc"
#include "zscript/menus/Dialogue/DialogueMenu.zsc"
#include "zscript/menus/dialogue/DialogueNext.zsc"

// TEST BOSS
#include "zscript/bosses/0_testboss.zsc"

class ReverseViewHandler : StaticEventHandler
{
    override void RenderOverlay(RenderEvent e)
    {
        // set the player's timer up correctly (more-than-1-tick precision)
        PlayerInfo p = players[consoleplayer];
        
        if (p.mo.CountInv("TestScreenPower") > 0)
        {
            Shader.SetEnabled(p, "cartoonshader", true);
        }
        else
        {
            Shader.SetEnabled(p, "cartoonshader", false);
        }
    }
}

class ReverseScreenPower : Powerup { Default { powerup.duration -30; } }

class TestScreenPower : ReverseScreenPower {}
