version "4.3"

#include "zscript/7_HUD/AREAGStatusBar.zsc"

#include "zscript/__prototypes/definitions.zsc"
#include "zscript/6_maptools/0_mapdata/mapdata.entity.zsc"
#include "zscript/6_maptools/0_mapdata/mapdata.data.zsc"
#include "zscript/6_maptools/0_mapdata/mapdata.repo.zsc"
#include "zscript/6_maptools/actors/areagate.zsc"
#include "zscript/6_maptools/actors/blocks.zsc"
#include "zscript/6_maptools/actors/doormanager.zsc"
#include "zscript/6_maptools/actors/savepoint.zsc"
#include "zscript/6_maptools/actors/shop.zsc"
#include "zscript/6_maptools/actors/switches.zsc"
#include "zscript/6_maptools/actors/tablet.zsc"
#include "zscript/6_maptools/actors/pitsector.zsc"
#include "zscript/6_maptools/actors/breakwall.zsc"
#include "zscript/6_maptools/1_sectorgraph/roomcontroller.zsc"
#include "zscript/6_maptools/1_sectorgraph/automap.repo.zsc"
#include "zscript/6_maptools/1_sectorgraph/automap.entity.zsc"

#include "zscript/__prototypes/currency.zsc"
#include "zscript/__prototypes/basicinventory.zsc"

#include "zscript/0_player/__protoplayer.zsc"
#include "zscript/0_player/0_playerbase.zsc"
#include "zscript/0_player/1_playermove.zsc"
#include "zscript/0_player/2_playerhealth.zsc"
#include "zscript/0_player/3_playerstatus.zsc"

#include "zscript/1_weapons/0_prototype.zsc"
#include "zscript/1_weapons/0_subweapons/1_knives.zsc"
#include "zscript/1_weapons/0_subweapons/2_dynamite.zsc"
#include "zscript/1_weapons/1_inventory/1_drone.zsc"
#include "zscript/1_weapons/1_inventory/2_horn.zsc"
#include "zscript/1_weapons/2_mainweapons/1_whip.zsc"
#include "zscript/1_weapons/2_mainweapons/2_steeltyrant.zsc"
#include "zscript/1_weapons/2_mainweapons/4_tribalshield.zsc"

#include "zscript/2_treasures/keys.zsc"

#include "zscript/3_artifice/boots.zsc"

#include "zscript/4_traps/speartrap.zsc"
#include "zscript/4_traps/darttrap.zsc"
#include "zscript/4_traps/lasertrap.zsc"

#include "zscript/5_monsters/0_basicenemy.zsc"
#include "zscript/5_monsters/1_golem.zsc"
#include "zscript/5_monsters/2_glowfly.zsc"
#include "zscript/5_monsters/zsctempimp.zsc"

#include "zscript/menutools.zsc"

