class BasicPassive : BasicInventory
{
    String clsName;

    virtual void definePickup() {}

    override void BasicPickup(Actor toucher) {
        definePickup();
        AREAGPlayerPawn plr = AREAGPlayerPawn(toucher);
        plr.pushPassiveEffect(clsName);
    }
}

class PlayerPassive : Thinker
{
    mixin AREAG_Common;
    virtual void passiveTick(AREAGPlayerPawn plr) {}
    virtual void onRemove(AREAGPlayerPawn plr) {}
}
